name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
      - name: Remove PS3 and Wii files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5 -s 4073741823
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
      - name: Remove Xbox and Wii files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-PS3
          path: _build/ps3
