name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
      - name: Get current commit SHA and replace DEVBUILD STRING
        id: get_commit
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/eng/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/deu/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/esl/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/fre/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/ita/locale_updates.dta
      - name: Remove PS3 and Wii files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5 -s 4073741823
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
      - name: Get current commit SHA and replace DEVBUILD STRING
        id: get_commit
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/eng/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/deu/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/esl/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/fre/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/ita/locale_updates.dta
      - name: Remove Xbox and Wii files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-PS3
          path: _build/ps3

  build_wii_patcher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
      - name: Get current commit SHA and replace DEVBUILD STRING
        id: get_commit
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/eng/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/deu/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/esl/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/fre/locale_updates.dta
          sed -i 's/DEVBUILD/${{ env.COMMIT_SHA }}/g' _ark/ui/locale/ita/locale_updates.dta
      - name: Remove Xbox and PS3 files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_ps3" -type f -delete
      - name: Create necessary directories and copy files for patcher
        run: |
          mkdir -p ./_build/wii/ultimate_files/sys/
          mkdir -p ./_build/wii/ultimate_files/files/gen/
          mkdir -p ./_build/wii/iso
          mkdir -p ./_build/wii/wit
          cp dependencies/patch/main.dol ./_build/wii/ultimate_files/sys/main.dol
          cp dependencies/patch/setup.txt ./_build/wii/ultimate_files/setup.txt
          cp _build/wii_rebuild_files/main_wii.hdr ./_build/wii/ultimate_files/files/gen/main_wii.hdr
          cp -r dependencies/wii-patcher/* ./_build/wii
          cp -r dependencies/wit/* ./_build/wii/wit
          cp -r iso/* ./_build/wii/iso

      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/wii/ultimate_files/files/gen -n "patch_wii" -e -v 5 -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GDRBUL-Wii-Patcher
          path: _build/wii
